---
- name: This is to add user on instances
  hosts: localhost

  tasks:
  - name: Create pool
    bigip_pool:
      state: present
      name: anishtest
      partition: Common
      lb_method: least-connections-member
      slow_ramp_time: 120
      provider:
        server: "{{ lookup('cypher','secret=secret/poolserver') }}"
        user: "{{ lookup('cypher','secret=secret/pooluser') }}"
        password: "{{ lookup('cypher','secret=secret/poolaccess') }}"
        validate_certs: no
        server_port: 8443
    delegate_to: localhost